# Generated by Django 3.1.7 on 2021-02-25 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'verbose_name': 'Телефонный Справочник', 'verbose_name_plural': 'Телефонный Справочник'},
        ),
    ]
