# Generated by Django 3.1.7 on 2021-03-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_auto_20210226_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'FEMALE'), (2, 'MALE')], null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='job_entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='job_experience_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='job_quit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
